version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: quizzes-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "quiz"
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql