spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?useUnicode=true&serverTimezone=UTC
    username: root
    password: password
  liquibase:
    change-log: classpath:liquibase-changelog.xml