spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?useUnicode=true&serverTimezone=UTC
    username: root
    password: password
  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 100
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:liquibase-changelog.xml