-- liquibase formatted sql
-- changeset teddy-bear1999:9

INSERT INTO quiz_question (quiz_id, content, option_a, option_b, option_c, option_d, answer)
VALUES (13, "Which planet is known as the 'Red Planet'?", "Jupiter", "Mars", "Saturn", "Earth", 2),
       (13, "Who wrote the novel 'Pride and Prejudice'?", "Jane Austen", "Charlotte Bronte", "Mary Shelley",
        "Virginia Woolf", 1),
       (13, "In which year did the Titanic sink?", "1905", "1912", "1918", "1922", 2),
       (13, "Which element has the chemical symbol 'Au'?", "Silver", "Gold", "Aluminum", "Argon", 2),
       (13, "What is the capital city of Australia?", "Sydney", "Melbourne", "Brisbane", "Canberra", 4),
       (13, "Who is known as the father of modern physics?", "Albert Einstein", "Isaac Newton", "Nikola Tesla",
        "Stephen Hawking", 1),
       (13, "In which language is the phrase 'C'est la vie'?", "Spanish", "French", "Italian", "German", 2),
       (13, "Which sport is played at Wimbledon?", "Baseball", "Football", "Tennis", "Basketball", 3),
       (13, "Who painted the Mona Lisa?", "Leonardo da Vinci", "Michelangelo", "Pablo Picasso", "Vincent van Gogh", 1),
       (13, "What is the largest mammal?", "Elephant", "Blue Whale", "Giraffe", "Rhino", 2),

       (14, "What is the square root of 64?", "6", "7", "8", "9", 3),
       (14, "If a triangle has one angle of 90 degrees, what type of triangle is it?", "Equilateral", "Isosceles",
        "Scalene", "Right", 4),
       (14, "What is \(5^3\)?", "15", "125", "60", "25", 2),
       (14, "What is the result of 12 x 9?", "102", "118", "108", "98", 3),
       (14, "What is the derivative of \(x^2\)?", "x", "2x", "x^2", "2", 2),
       (14, "What is the value of \(\pi\) up to three decimal places?", "3.142", "3.141", "3.145", "3.149", 1),
       (14, "Solve for x: 2x + 4 = 12", "4", "5", "3", "2", 1),
       (14, "Which of these numbers is prime?", "21", "22", "23", "24", 3),
       (14, "If a circle has a radius of 7, what is its diameter?", "7", "14", "21", "28", 2),
       (14, "What is the smallest positive integer?", "0", "1", "-1", "2", 2),

       (15, "What is the smallest unit of life?", "Molecule", "Cell", "Atom", "Organism", 2),
       (15, "Which planet is known for its rings?", "Venus", "Mars", "Jupiter", "Saturn", 4),
       (15, "What is the chemical symbol for water?", "W", "WO", "H2O", "HO2", 3),
       (15, "Who is known for the theory of relativity?", "Newton", "Galileo", "Einstein", "Curie", 3),
       (15, "What does DNA stand for?", "Deoxyribo Nucleic Acid", "Dioxyribo Neutral Acid", "Deoxyribo Natural Acid",
        "Dioxyribo Nucleic Acid", 1),
       (15, "Which gas do plants absorb from the atmosphere?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen", 1),
       (15, "What is the process by which plants make their own food using sunlight?", "Respiration", "Digestion",
        "Photosynthesis", "Fermentation", 3),
       (15, "Which of these is NOT a mammal?", "Dolphin", "Whale", "Shark", "Bat", 3),
       (15, "What is the most abundant gas in Earth's atmosphere?", "Oxygen", "Carbon Dioxide", "Nitrogen", "Helium",
        3),
       (15, "Which scientist proposed the three laws of motion?", "Einstein", "Galileo", "Newton", "Faraday", 3),
       (15, "What force keeps us on the ground?", "Magnetic", "Friction", "Gravitational", "Electrostatic", 3),
       (15, "What part of the cell is responsible for producing energy?", "Nucleus", "Cell Wall", "Cytoplasm",
        "Mitochondria", 4),
       (15, "Which is the hardest substance in the human body?", "Bones", "Nails", "Teeth Enamel", "Cartilage", 3),
       (15, "How many bones are in the adult human body?", "206", "305", "415", "512", 1),
       (15, "Which element is represented by the symbol 'K'?", "Potassium", "Krypton", "Ketamine", "Kilogram", 1);

